### ISSUE TITLE
[PATCH] fix spelling error in manpage

### ISSUE THREAD

**Issue by carnil** [bradchoate/text-textile#13]
Hi,

In Debian we are currently applying the following patch to Text-Textile.
We thought you might be interested in it too.

The patch is located at http://anonscm.debian.org/gitweb/?p=pkg-perl/packages/libtext-textile-perl.git;a=blob;f=debian/patches/fix-spelling-error-in-manpage.patch;hb=HEAD

```
Fix spelling errors in manpage
Origin: vendor
Author: Salvatore Bonaccorso <carnil@debian.org>
Last-Update: 2014-07-27
```

Thanks in advance,
  Salvatore Bonaccorso, Debian Perl Group

**Comment by bradchoate** [comment]
Thanks! I've applied those changes. Will be included in the next release.
