### ISSUE TITLE
"Use of uninitialized value" warning for images

### ISSUE THREAD

**Issue by ghost** [bradchoate/text-textile#6]
perl -e 'use Text::Textile qw(textile); print textile("!/path/to/image!")'
Use of uninitialized value $w in string eq at /usr/share/perl5/Text/Textile.pm line 1557.
Use of uninitialized value $h in string eq at /usr/share/perl5/Text/Textile.pm line 1558.

Nothing more to say.

**Comment by bradchoate** [comment]
Can no longer reproduce this.
